### ISSUE TITLE
bug: Recipe builds are failing on signing step

### ISSUE THREAD

**Issue by J3rr1ck** [ublue-os/startingpoint#29] opened 2023-04-18 16:57 UTC
hey all after following the manual setup directions I'm getting the following error back from actions 
`    DOCKER_METADATA_OUTPUT_BAKE_FILE: /tmp/docker-actions-toolkit-dOlNP5/docker-metadata-action-bake.json
    TAGS: sha256:8a80680feaecbd9226ec7894aff4f6bdd449e3a565e4f76cc03ba79b1927c99e
    COSIGN_EXPERIMENTAL: false
    COSIGN_PRIVATE_KEY: ***
653 cosign.key
Error: signing [ghcr.io/j3rr1ck/Gnos_Linux_Nvidia@sha256:8a80680feaecbd9226ec7894aff4f6bdd449e3a565e4f76cc03ba79b1927c99e]: getting signer: reading key: unsupported pem type: ENCRYPTED SIGSTORE PRIVATE KEY
main.go:74: error during command execution: signing [ghcr.io/j3rr1ck/Gnos_Linux_Nvidia@sha256:8a80680feaecbd9226ec7894aff4f6bdd449e3a565e4f76cc03ba79b1927c99e]: getting signer: reading key: unsupported pem type: ENCRYPTED SIGSTORE PRIVATE KEY
Error: Process completed with exit code 1.`

I tried swapping in both passworded and non-passworded keys just to see if that was the problem but the error is consistent across both 
am I missing something obvious here?

**Comment by johnrellim** [comment] 2023-04-20 03:47
I am also having issues with the signing. At first, my keys were coming out encrypted, which the docs say won't work. You can tell they are encrypted when the `.key` starts with `BEGIN ENCRYPTED SIGSTORE PRIVATE KEY`. 

I, somehow, got an unencrypted key pair, but I still can't sign the image. The error I am getting is: 

```
Error: signing [ghcr.io/johnrellim/imageName@hash getting signer: reading key: unsupported pem type: SIGSTORE PRIVATE KEY
main.go:74: error during command execution: signing [ghcr.io/johnrellim/image@hash getting signer: reading key: unsupported pem type: SIGSTORE PRIVATE KEY
```

Are there any settings within Cosign that need to be adjusted? Is there an issue with the new versions? I reinstalled it recently and am currently using  on this version of Cosign: 

```
GitVersion:    v2.0.1
GitCommit:     8faaee4d2b5f65678eb0831a8a3d5990a0271d3a
GitTreeState:  clean
BuildDate:     2023-04-06T19:10:33Z
```

Any ideas?

**Comment by vaparetia** [comment] 2023-04-21 05:02
I'm also getting an error with the signing step.

>COSIGN_PRIVATE_KEY: ***
653 cosign.key
Error: signing [ghcr.io/vaparetia/custom-gnome-theme@sha256:3f02d5cd6fd2de60d4736b6a67a054f1a0926cf9e[41](https://github.com/vaparetia/custom-gnome-theme/actions/runs/4761553298/jobs/8462911244#step:15:42)adfbce344c[42](https://github.com/vaparetia/custom-gnome-theme/actions/runs/4761553298/jobs/8462911244#step:15:43)846e67579]: getting signer: reading key: unsupported pem type: ENCRYPTED SIGSTORE PRIVATE KEY
main.go:74: error during command execution: signing [ghcr.io/vaparetia/custom-gnome-theme@sha256:3f02d5cd6fd2de60d4736b6a67a054f1a0926cf9e41adfbce344c42846e67579]: getting signer: reading key: unsupported pem type: ENCRYPTED SIGSTORE PRIVATE KEY
Error: Process completed with exit code 1.
>
Not entirely sure how to remedy this issue.

I'm a noob so, I'm basically useless lol :laughing:

**Comment by ashylily** [comment] 2023-04-21 08:44
I ran into this problem too and it seems cosign has changed the format of the key file but the signing (github task?) doesn't support it yet.

I worked it around by editing my key replacing `ENCRYPTED SIGSTORE PRIVATE KEY` with `ENCRYPTED COSIGN PRIVATE KEY` (the old format) and uploading the key again.

**Comment by johnrellim** [comment] 2023-04-21 12:38
I can confirm that making the above change to the `SIGNING_SECRET` works.

 Another possible workaround would be to use an earlier version of Cosign than 2.0.1.

**Comment by vaparetia** [comment] 2023-04-21 21:03
> I can confirm that making the above change to the `SIGNING_SECRET` works.
> 
> Another possible workaround would be to use an earlier version of Cosign than 2.0.1.

Changing to Cosign 2.0.0 worked like a charm. 



> I ran into this problem too and it seems cosign has changed the format of the key file but the signing (github task?) doesn't support it yet.
> 
> I worked it around by editing my key replacing `ENCRYPTED SIGSTORE PRIVATE KEY` with `ENCRYPTED COSIGN PRIVATE KEY` (the old format) and uploading the key again.

That didn't work for me unfortunately, but installing cosign 2.0.0 and resigning did fix my issue. 



All, Thanks for pointing me in the right direction!

**Comment by imatsatsos** [comment] 2023-04-22 16:02
I was trying to generate my key on Windows 10 using Powershell. When it prompts to press `Enter` instead of typing a password I was doing just that, following the instruction on the site, but I believe that Windows 10 powershell passes a CRLF return character instead of a LF character. Maybe that affected the password entering step. Another thing to note is that git prompted me that it would replace LF to CRLF characters on my cosign.pub next time it touched it ( I believe that would be on the git-push ). When I moved the signing steps on my Linux machine, git stopped complaining for CRLF characters and I managed to finally pass signing the build.

To sum what I am trying to say. Either cosing on windows (I used cosign 2.0.1) has issues or the CRLF LF difference comes at play.

**Comment by EinoHR** [comment] 2023-04-22 17:38
I didn't even think somebody would try this on Windows... I'd recommend WSL for most dev things, just in case.

**Comment by EinoHR** [comment] 2023-04-24 15:04
I marked this as help wanted, because I am not that familiar with the whole cosign & GHA part of things. If you can report with information not available here or provide more clarity, please comment, but don't just +1 (you could react to this comment or smth).

I encourage you to manually regenerate the cosign keys if this problem happens to you, and only comment afterward if the issue is not fixed.

**Closed** 2023-05-09 14:41 UTC
Labels: bug, help wanted
